### ISSUE TITLE
Offer various styles

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/rplus-wp-team-list#11]
We could add a new `style`param in the shortcode and template tag where the user could choose between a couple of predefined styles (i.e. some more stylish CSS).

**Comment by neverything** [comment]
I don't think this is necessary, our team list plugin is sort of a bare basic thing that a user needs to be comfortable to add their own styling anyways and probably changes the template too. What we could do is adding a beautiful default CSS that can be disabled via a) a filter and b) an option.

More opinions?

**Comment by velthy** [comment]
I'd choose a beautiful default CSS, which can be disabled.
