### ISSUE TITLE
Easy way to Filter by last_name?

### ISSUE THREAD

**Issue by remeyd** [wearerequired/rplus-wp-team-list#15]
Hi,
Thanks for your Plugin!
Is there a way to filter by last_name, instead of display_name?
Best,
Rémi

**Comment by swissspidy** [comment]
Hey there

If you're using the shortcode you should be able to use something like this:

`[rplus_team_list role="Author" orderby="last_name" order="desc"]`

Until we add a similar option to the widget, you can use the `rplus_wp_team_list_args` filter provided by the plugin (see https://github.com/wearerequired/rplus-wp-team-list/blob/3ce5f6f91c97ef6055acfc99d6f3e3f480a07f2c/class-rplus-wp-team-list.php#L320) to change all query arguments.

**Comment by remeyd** [comment]
Thank a lot you for the answer!

I use this shortcode that way, but it doesn't seem to work!

https://github.com/wearerequired/rplus-wp-team-list/blob/3ce5f6f91c97ef6055acfc99d6f3e3f480a07f2c/templates/rplus-wp-team-list.php#55

I put 
         echo esc_html( get_user_meta( $user->ID, 'last_name', true ) . " " . get_user_meta( $user->ID, 'first_name', true )); 

instead of :
	 echo esc_html( $user->data->display_name );

Now I would like to diplay my users by their last_name in alphabetical order...

Do you have an idea to do this?
I'm not good yet with hooks...

**Comment by swissspidy** [comment]
@remeyd Can you provide the exact shortcode you're using so I can try to reproduce your issue?

**Comment by remeyd** [comment]
Hi Pascal,

Here the exact shortcode:
[rplus_team_list role="Contributor" orderby="last_name" order="asc"]

And here the result :
http://www.lasantesurtout.com/comite-medical/

It's not exactly an alphabetical order.

Thanks for your help!


Rémi Eydaleine


2015-05-28 13:28 GMT+02:00 Pascal Birchler <notifications@github.com>:

**Comment by swissspidy** [comment]
@remeyd I can confirm that this doesn't work. Apparently ordering by last name isn't really possible inside WordPress, so it falls back to order by username. But no worries, I added a workaround so your shortcode will work. :tada:

I just deployed version 1.0.4 of the plugin to WordPress.org. You should see an update notice in your WordPress admin shortly.

Thanks again for reporting this! If you're happy with the plugin, please consider submitting a review on WordPress.org. That would be awesome!

Also, let me know if you're interested in providing French translation files for the plugin :)

**Comment by remeyd** [comment]
Thanks a lot :)
