### ISSUE TITLE
Shortcode UI for both shortcodes

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/rplus-wp-team-list#23]
In 2.0.0 I introduced the non-prefixed `[wp_team_list]` shortcode (that we can use in the future to add new things) and set up Shortcake for both.

Now when adding shortcodes through the UI you'll see two suggested team list shortcodes.

We should only add 1 or perhaps state that the old one is deprecated (i.e. change the title / description)

**Comment by hubeRsen** [comment]
We should simply remove this one `shortcode_ui_register_for_shortcode( 'rplus_team_list', $shortcode_ui_args );` - Ok, existing shortcodes of this type `rplus_team_list ` wouldn't be displayed correctly via shortcake, but is that "a case" ?

**Comment by ocean90** [comment]
How about adding a "[deprecated]" suffix for the minor release and in 2.1 we can remove it?

**Comment by swissspidy** [comment]
Sounds good to me. I doubt that many people use this plugin together with Shortcake anyway.
