### ISSUE TITLE
Invalid CSS class for user roles

### ISSUE THREAD

**Issue by ocean90** [wearerequired/rplus-wp-team-list#38]
Currently the display name of a role is used for the class name. Since a display name can include spaces the CSS class isn't what you'd expect.

```html
<div class="wp-team-member wp-team-list-item author-5 role-Role with Spaces">
```

For the CSS class we should use the slug/key of the role. Or sanitize the display name for use as a CSS class. How should we handle that in terms of back-compat?

**Comment by swissspidy** [comment]
With 100+ active installs I doubt that we have to care that much about backward compatibility. I doubt that someones is targeting a team list item with a role in it that has spaces. If so, they would notice this bug. Also, CSS selectors are case insensitive in general.

**Comment by ocean90** [comment]
> CSS selectors are case insensitive in general.

But HTML class names are not, see last paragraph on https://www.w3.org/TR/html5/disabled-elements.html#case-sensitivity.

Another issue with using display names: The classes are different per language.

**Comment by swissspidy** [comment]
So…what hinders us from fixing it?

**Comment by ocean90** [comment]
Me trying to find a good name for the method. Technically it's `get_user_role()`, but that one already exists and returns the display name... 🤷‍♀️

**Comment by grappler** [comment]
I would just keep the method name and change the parameter from name to slug.

**Comment by swissspidy** [comment]
^ Just thought the same when reviewing #39. That means the function doesn't do 1 thing alone anymore, but the function isn't too complex anyway.
