### ISSUE TITLE
Simplify template loading

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/rplus-wp-team-list#9]
This idea originated in #2:

> I don't think people should be able to change the template via rplus_wp_team_list(). Also, the widget template is practically equal with the default one. Why not unify them, remove the template argument altogether and only use a filter?
> 
> Of course we could still detect the existence of a template file in the theme's folder, but this means telling people how they should structure their templates. Nobody stores this plugin's template in the root folder of a theme.

Also:

> I like how BuddyPress loads templates using `bp_get_template_part` and `bp_locate_template`. Maybe we can implement a simpler version of this.

**Comment by neverything** [comment]
@swissspidy thanks for writing your idea for the template loader down. I agree and think you can go ahead and implement a more suitable template loading. As long as I still can provide a different template for the widget and the template tag/shortcode somehow, I am happy.

**Comment by swissspidy** [comment]
Maybe we could unify the templates? Would make it easier. It looks like the only difference of the current two templates is the output of the user's role and the detail link. These would make great options to toggle in the back-end. See also #12.
